#!/bin/bash

docker run -ti --rm -d \
           -e DISPLAY=$DISPLAY \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -v `pwd`/conf/netbeans:/home/developer/.netbeans \
           -v `pwd`:/workspace \
           ide:latest
